import { Reader, createC2pa } from '@contentauth/c2pa-web';
import type { Manifest, ManifestStore, ValidationStatus } from '@contentauth/c2pa-types';
import type { Evidence, MediaKind, Signal, SignalResult } from '@verity/core';

let c2paPromise: ReturnType<typeof createC2pa> | undefined;

function getC2pa(): ReturnType<typeof createC2pa> {
  // Assets are copied from @contentauth/c2pa-web into dist/assets by the vite plugin.
  c2paPromise ??= createC2pa({
    wasmSrc: chrome.runtime.getURL('assets/c2pa_bg.wasm'),
    workerSrc: new URL(chrome.runtime.getURL('assets/c2pa_worker.js')),
  });
  return c2paPromise;
}

// C2PA digitalSourceType → plain-language meaning. A signed AI manifest is still
// "verified" — the signature authenticates the claim, including an AI origin.
const SOURCE_TYPES: Record<string, string> = {
  digitalCapture: 'Captured by a digital device',
  digitizedNegativeFilm: 'Digitized from film',
  trainedAlgorithmicMedia: 'Declared AI-generated',
  compositeWithTrainedAlgorithmicMedia: 'Contains AI-generated content',
  algorithmicMedia: 'Generated by software',
  softwareImage: 'Created in software',
  digitalArt: 'Digital art',
  virtualRecording: 'Virtual recording',
  compositeCapture: 'Composite of captured frames',
  compositeSynthetic: 'Composite including generated content',
};

const MIME_BY_KIND: Record<MediaKind, string> = {
  image: 'image/jpeg',
  video: 'video/mp4',
  audio: 'audio/mpeg',
};

function sourceTypeLabel(uri: string): string {
  const key = uri.split('/').pop() ?? uri;
  return SOURCE_TYPES[key] ?? `Source type: ${key}`;
}

function plainAction(action: string): string {
  return action.replace(/^c2pa\./, '').replace(/_/g, ' ');
}

function collectEvidence(store: ManifestStore, manifest: Manifest): Evidence[] {
  const evidence: Evidence[] = [];
  const seen = new Set<string>();
  const push = (e: Evidence): void => {
    if (seen.has(e.label)) return;
    seen.add(e.label);
    evidence.push(e);
  };

  const sig = manifest.signature_info;
  if (sig?.issuer || sig?.common_name) {
    push({ label: `Signed by ${sig.issuer ?? sig.common_name}`, ...(sig.time ? { detail: sig.time } : {}) });
  }
  if (manifest.claim_generator) {
    push({ label: `Produced by ${manifest.claim_generator}` });
  }

  for (const a of manifest.assertions ?? []) {
    const data = a.data as { actions?: Array<{ action?: string; digitalSourceType?: string }> } | undefined;
    if (a.label !== 'c2pa.actions' || !data?.actions) continue;
    const names = data.actions
      .map((x) => x.action)
      .filter((x): x is string => Boolean(x))
      .map(plainAction);
    if (names.length) push({ label: 'History', detail: names.join(', ') });
    for (const act of data.actions) {
      if (act.digitalSourceType) push({ label: sourceTypeLabel(act.digitalSourceType) });
    }
  }

  for (const ing of manifest.ingredients ?? []) {
    for (const t of ing.data_types ?? []) {
      const ty = (t as { type?: string }).type;
      if (ty) push({ label: `Ingredient: ${sourceTypeLabel(ty).toLowerCase()}` });
    }
  }

  return evidence;
}

function validationFailures(store: ManifestStore): ValidationStatus[] {
  return [
    ...(store.validation_status ?? []),
    ...(store.validation_results?.activeManifest?.failure ?? []),
  ].filter((f) => f.success !== true);
}

export const c2paSignal: Signal = {
  id: 'c2pa',
  name: 'Provenance (C2PA)',
  supports: () => true,
  async analyze(media): Promise<SignalResult> {
    const base = { signalId: this.id, signalName: this.name };
    const c2pa = await getC2pa();
    const format = media.blob.type || MIME_BY_KIND[media.kind];
    const reader = await Reader.fromBlob(c2pa, format, media.blob);

    if (!reader) {
      return {
        ...base,
        outcome: 'neutral',
        confidence: 0,
        summary: 'No provenance data attached to this media.',
        evidence: [],
      };
    }

    try {
      const store = await reader.manifestStore();
      const manifest = await reader.activeManifest();
      const evidence = collectEvidence(store, manifest);
      const failures = validationFailures(store);

      if (store.validation_state === 'Invalid' || failures.length > 0) {
        for (const f of failures) {
          evidence.push({
            label: `Validation failed: ${f.code}`,
            ...(f.explanation ? { detail: f.explanation } : {}),
          });
        }
        return {
          ...base,
          outcome: 'negative',
          confidence: 0.9,
          conclusive: true,
          summary: 'A provenance record exists but failed signature validation.',
          evidence,
        };
      }

      return {
        ...base,
        outcome: 'positive',
        confidence: 0.95,
        conclusive: true,
        summary: 'Cryptographically signed provenance is present and valid.',
        evidence,
      };
    } finally {
      await reader.free();
    }
  },
};
