import { createC2pa } from 'c2pa-node';
import { sniffMime } from '@verity/core';
import type { Evidence, MediaKind, Signal, SignalResult } from '@verity/core';

// c2pa-node ships precompiled neon bindings; one instance per process.
const c2pa = createC2pa();

const MIME_BY_KIND: Record<MediaKind, string> = {
  image: 'image/jpeg',
  video: 'video/mp4',
  audio: 'audio/mpeg',
};

// Same plain-language mapping as the extension signal — keep in sync.
const SOURCE_TYPES: Record<string, string> = {
  digitalCapture: 'Captured by a digital device',
  digitizedNegativeFilm: 'Digitized from film',
  trainedAlgorithmicMedia: 'Declared AI-generated',
  compositeWithTrainedAlgorithmicMedia: 'Contains AI-generated content',
  algorithmicMedia: 'Generated by software',
  softwareImage: 'Created in software',
  digitalArt: 'Digital art',
  virtualRecording: 'Virtual recording',
  compositeCapture: 'Composite of captured frames',
  compositeSynthetic: 'Composite including generated content',
};

function sourceTypeLabel(uri: string): string {
  const key = uri.split('/').pop() ?? uri;
  return SOURCE_TYPES[key] ?? `Source type: ${key}`;
}

/**
 * Server-side provenance check (bot pipeline). Same honesty rules as the
 * extension's c2pa signal: no manifest is neutral, a manifest that fails
 * validation is conclusive-negative, a valid signature is conclusive-positive.
 */
export const c2paSignal: Signal = {
  id: 'c2pa',
  name: 'Provenance (C2PA)',
  supports: () => true,
  async analyze(media): Promise<SignalResult> {
    const base = { signalId: this.id, signalName: this.name };
    const buffer = Buffer.from(await media.blob.arrayBuffer());
    const mimeType =
      sniffMime(new Uint8Array(buffer)) ?? media.blob.type ?? MIME_BY_KIND[media.kind];

    let store;
    try {
      store = await c2pa.read({ buffer, mimeType });
    } catch {
      // Unparseable container (e.g. a format c2pa doesn't support) means no
      // readable provenance — neutral, not an error.
      store = null;
    }

    if (!store?.active_manifest) {
      return {
        ...base,
        outcome: 'neutral',
        confidence: 0,
        summary: 'No provenance data attached to this media.',
        evidence: [],
      };
    }

    const manifest = store.active_manifest;
    const evidence: Evidence[] = [];
    const sig = manifest.signature_info;
    if (sig?.issuer || sig?.common_name) {
      evidence.push({
        label: `Signed by ${sig.issuer ?? sig.common_name}`,
        ...(sig?.time ? { detail: String(sig.time) } : {}),
      });
    }
    if (manifest.claim_generator) {
      evidence.push({ label: `Produced by ${manifest.claim_generator}` });
    }
    for (const a of manifest.assertions ?? []) {
      const data = a.data as { actions?: Array<{ digitalSourceType?: string }> } | undefined;
      if (a.label !== 'c2pa.actions' || !data?.actions) continue;
      for (const act of data.actions) {
        if (act.digitalSourceType) evidence.push({ label: sourceTypeLabel(act.digitalSourceType) });
      }
    }

    const failures = store.validation_status ?? [];
    if (failures.length > 0) {
      for (const f of failures) {
        evidence.push({
          label: `Validation failed: ${f.code}`,
          ...(f.explanation ? { detail: f.explanation } : {}),
        });
      }
      return {
        ...base,
        outcome: 'negative',
        confidence: 0.9,
        conclusive: true,
        summary: 'A provenance record exists but failed signature validation.',
        evidence,
      };
    }

    return {
      ...base,
      outcome: 'positive',
      confidence: 0.95,
      conclusive: true,
      summary: 'Cryptographically signed provenance is present and valid.',
      evidence,
    };
  },
};
